const mockSearchedUsers = {
    "total_count": 5,
    "incomplete_results": false,
    "items": [
      {
        "login": "jawad",
        "id": 73117877,
        "node_id": "MDQ6VXNlcjczMTE3ODc3",
        "avatar_url": "https://avatars1.githubusercontent.com/u/73117877?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jawad",
        "html_url": "https://github.com/jawad",
        "followers_url": "https://api.github.com/users/jawad/followers",
        "following_url": "https://api.github.com/users/jawad/following{/other_user}",
        "gists_url": "https://api.github.com/users/jawad/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jawad/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jawad/subscriptions",
        "organizations_url": "https://api.github.com/users/jawad/orgs",
        "repos_url": "https://api.github.com/users/jawad/repos",
        "events_url": "https://api.github.com/users/jawad/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jawad/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "jawad6233",
        "id": 6875504,
        "node_id": "MDQ6VXNlcjY4NzU1MDQ=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/6875504?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jawad6233",
        "html_url": "https://github.com/jawad6233",
        "followers_url": "https://api.github.com/users/jawad6233/followers",
        "following_url": "https://api.github.com/users/jawad6233/following{/other_user}",
        "gists_url": "https://api.github.com/users/jawad6233/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jawad6233/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jawad6233/subscriptions",
        "organizations_url": "https://api.github.com/users/jawad6233/orgs",
        "repos_url": "https://api.github.com/users/jawad6233/repos",
        "events_url": "https://api.github.com/users/jawad6233/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jawad6233/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "jawad846",
        "id": 33896731,
        "node_id": "MDQ6VXNlcjMzODk2NzMx",
        "avatar_url": "https://avatars1.githubusercontent.com/u/33896731?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jawad846",
        "html_url": "https://github.com/jawad846",
        "followers_url": "https://api.github.com/users/jawad846/followers",
        "following_url": "https://api.github.com/users/jawad846/following{/other_user}",
        "gists_url": "https://api.github.com/users/jawad846/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jawad846/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jawad846/subscriptions",
        "organizations_url": "https://api.github.com/users/jawad846/orgs",
        "repos_url": "https://api.github.com/users/jawad846/repos",
        "events_url": "https://api.github.com/users/jawad846/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jawad846/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "ihack4falafel",
        "id": 17316888,
        "node_id": "MDQ6VXNlcjE3MzE2ODg4",
        "avatar_url": "https://avatars0.githubusercontent.com/u/17316888?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ihack4falafel",
        "html_url": "https://github.com/ihack4falafel",
        "followers_url": "https://api.github.com/users/ihack4falafel/followers",
        "following_url": "https://api.github.com/users/ihack4falafel/following{/other_user}",
        "gists_url": "https://api.github.com/users/ihack4falafel/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ihack4falafel/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ihack4falafel/subscriptions",
        "organizations_url": "https://api.github.com/users/ihack4falafel/orgs",
        "repos_url": "https://api.github.com/users/ihack4falafel/repos",
        "events_url": "https://api.github.com/users/ihack4falafel/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ihack4falafel/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "jawadsh123",
        "id": 15520960,
        "node_id": "MDQ6VXNlcjE1NTIwOTYw",
        "avatar_url": "https://avatars1.githubusercontent.com/u/15520960?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jawadsh123",
        "html_url": "https://github.com/jawadsh123",
        "followers_url": "https://api.github.com/users/jawadsh123/followers",
        "following_url": "https://api.github.com/users/jawadsh123/following{/other_user}",
        "gists_url": "https://api.github.com/users/jawadsh123/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jawadsh123/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jawadsh123/subscriptions",
        "organizations_url": "https://api.github.com/users/jawadsh123/orgs",
        "repos_url": "https://api.github.com/users/jawadsh123/repos",
        "events_url": "https://api.github.com/users/jawadsh123/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jawadsh123/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      }
    ]
}

export default mockSearchedUsers;