const mockFollowers = [
  {
    "login": "BENsoufianeBEN",
    "id": 56634774,
    "node_id": "MDQ6VXNlcjU2NjM0Nzc0",
    "avatar_url": "https://avatars1.githubusercontent.com/u/56634774?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/BENsoufianeBEN",
    "html_url": "https://github.com/BENsoufianeBEN",
    "followers_url": "https://api.github.com/users/BENsoufianeBEN/followers",
    "following_url": "https://api.github.com/users/BENsoufianeBEN/following{/other_user}",
    "gists_url": "https://api.github.com/users/BENsoufianeBEN/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/BENsoufianeBEN/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/BENsoufianeBEN/subscriptions",
    "organizations_url": "https://api.github.com/users/BENsoufianeBEN/orgs",
    "repos_url": "https://api.github.com/users/BENsoufianeBEN/repos",
    "events_url": "https://api.github.com/users/BENsoufianeBEN/events{/privacy}",
    "received_events_url": "https://api.github.com/users/BENsoufianeBEN/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "NajibTs",
    "id": 56634649,
    "node_id": "MDQ6VXNlcjU2NjM0NjQ5",
    "avatar_url": "https://avatars2.githubusercontent.com/u/56634649?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/NajibTs",
    "html_url": "https://github.com/NajibTs",
    "followers_url": "https://api.github.com/users/NajibTs/followers",
    "following_url": "https://api.github.com/users/NajibTs/following{/other_user}",
    "gists_url": "https://api.github.com/users/NajibTs/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/NajibTs/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/NajibTs/subscriptions",
    "organizations_url": "https://api.github.com/users/NajibTs/orgs",
    "repos_url": "https://api.github.com/users/NajibTs/repos",
    "events_url": "https://api.github.com/users/NajibTs/events{/privacy}",
    "received_events_url": "https://api.github.com/users/NajibTs/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "dasimems",
    "id": 65473511,
    "node_id": "MDQ6VXNlcjY1NDczNTEx",
    "avatar_url": "https://avatars0.githubusercontent.com/u/65473511?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dasimems",
    "html_url": "https://github.com/dasimems",
    "followers_url": "https://api.github.com/users/dasimems/followers",
    "following_url": "https://api.github.com/users/dasimems/following{/other_user}",
    "gists_url": "https://api.github.com/users/dasimems/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dasimems/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dasimems/subscriptions",
    "organizations_url": "https://api.github.com/users/dasimems/orgs",
    "repos_url": "https://api.github.com/users/dasimems/repos",
    "events_url": "https://api.github.com/users/dasimems/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dasimems/received_events",
    "type": "User",
    "site_admin": false
  }
]
  export default mockFollowers;